from django.db import models

# Create your models here.
class Output(models.Model):
    id=models.IntegerField(primary_key=True)
    title=models.CharField(max_length=255,null=True)
    year=models.IntegerField(null=True)
    journal=models.CharField(max_length=255,null=True)
    authors=models.TextField(null=True)
    genre=models.CharField(max_length=255,null=True)
    description=models.TextField(null=True)
    constructs=models.TextField(null=True)
    perspectives=models.TextField(null=True)
    context=models.TextField(null=True)
    study=models.TextField(null=True)
    levels=models.TextField(null=True)
    notes=models.TextField(null=True)
    findings=models.TextField(null=True)
    summary=models.TextField(null=True)
    insights=models.TextField(null=True)
    points=models.TextField(null=True)
    use=models.TextField(null=True)
    additional=models.TextField(null=True)

class Save(models.Model):
    id=models.AutoField(primary_key=True)
    title=models.CharField(max_length=255,null=True)
    year=models.IntegerField(null=True)
    journal=models.CharField(max_length=255,null=True)
    authors=models.TextField(null=True)
    genre=models.CharField(max_length=255,null=True)
    description=models.TextField(null=True)
    constructs=models.TextField(null=True)
    perspectives=models.TextField(null=True)
    context=models.TextField(null=True)
    study=models.TextField(null=True)
    levels=models.TextField(null=True)
    notes=models.TextField(null=True)
    findings=models.TextField(null=True)
    summary=models.TextField(null=True)
    insights=models.TextField(null=True)
    points=models.TextField(null=True)
    use=models.TextField(null=True)
    additional=models.TextField(null=True)