# Generated by Django 5.0 on 2024-05-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='notes',
        ),
    ]
