# Generated by Django 5.0 on 2024-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_output_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='additional',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='insights',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='points',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='use',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='save',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
