# Generated by Django 5.0 on 2024-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_output_additional_output_insights_output_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
