# Generated by Django 5.0 on 2024-05-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_save_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Output',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
